#-*- coding: utf-8 -*-

{
	"name": "Property Portal",
	"version": "1.0",
	"depends": [
		"base",
		"web",
		"website_payment",
		"website",
		"portal",
		"sale",
		"vit_property",
	],
	"author": "Akhmad Daniel Sembiring",
	"category": "Utility",
	"website": "http://vitraining.com",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "",
	"description": "",
	"data": [
		"security/ir.model.access.csv",
		"views/property_portal_signup.xml",
		"views/breadcrumbs.xml",
		"views/kalkulator_imbal_hasil.xml",
		"views/property_portal.xml",
		"views/property_portal_owner.xml",
		"views/property_portal_token.xml",
		"views/property_portal_investor.xml",
		"views/property_portal_marketplace.xml",
	],
	"assets": {
		'web.assets_frontend': [
			'vit_property_portal/static/src/js/count_token.js',
			'vit_property_portal/static/src/js/property_calculator.js',
			'vit_property_portal/static/src/js/yield_calculator.js',
			'vit_property_portal/static/src/js/property_form.js',
			'vit_property_portal/static/src/js/token_pagination.js',
			'vit_property_portal/static/src/js/token_generate.js',
			'vit_property_portal/static/src/js/property_image.js',
			'vit_property_portal/static/src/js/property_document.js',
			'vit_property_portal/static/src/js/token_resell.js',
			'vit_property_portal/static/src/css/property_portal.css',
			'vit_property_portal/static/src/css/input_range.css',
		],
	},
	"installable": True,
	"auto_install": False,
	"application": True,
	"odooVersion": 18,
}